config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  # get '/users/:id', to: 'users#show'
  # /users/3 -> Users controller, show action, params {id: '3'}
  resources :users, only: [:index, :show, :update]
  resources :friends, only: [:create,:destroy]

  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :bookmarks
  has_many :friends

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[twitter]

  validates :name, presence: true, length: {maximum: 50}

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image.gsub!("_normal", "") # assuming the user model has an image
      user.uid = auth.uid
      user.provider = auth.provider
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.search(term)
    if term
      where('name LIKE ?', "%#{term}%")
    else
      nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.search(params[:term])
    respond_to :js
  end

  def show
    @user = User.find(params[:id])
    set_meta_tags title: @user.name
    @posts = @user.posts.includes(:photos, :likes, :comments)
    @saved = Post.joins(:bookmarks).where("bookmarks.user_id=?", current_user.id).
      includes(:photos, :likes, :comments) if @user == current_user
    @user_is_friend = current_user.friends.map(&:friend_id).include?(params[:id].to_i)
  end

  def update
    @user = User.find(params[:id])
    image = Cloudinary::Uploader.upload(params[:images]["0"])['url']
    @user.update(image: image)
  end
end

app/views/users/_post.html.erb
<% posts.each do |post| %>
  <div class="col-4">
    <%= link_to post_path(post) do %>
      <div class="post-stat d-flex justify-content-center align-items-center">
        <span>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <%= post.likes.size %>
          <i class="ml-3 fa fa-comment" aria-hidden="true"></i>
          <%= post.comments.size %>
        </span>
      </div>
      <%= image_tag post.photos.first.image.url(:standard), class: "card-img-top image-preview" %>
    <% end %>
  </div>
<% end %>

app/views/users/_users_result.html.erb
<% if users.present? %>
  <% users.each do |user| %>
    <%= link_to user_path(user), class: "no-text-decoration normal-color" do %>
      <div class="search-result-item"><%= user.name %></div>
    <% end %>
  <% end %>
<% else %>
  <div class="p-3">
    No results found.
  </div>
<% end %>

app/views/users/index.js.erb
$("#users-result").html('<%= j render "users_result", {users: @users} %>')

app/views/users/show.html.erb
<div class="row justify-content-md-center profile-wrapper">
  <div class="col-md-4 text-center" data-toggle="modal" data-target="#exampleModal">
    <%= image_tag avatar_url(@user), width: '152', height: '152', class: "round-img" %>
  </div>
  <div class="col-md-8">
    <div class="row">
      <p class="username"><%= @user.name %></p>
      <% if @user == current_user %>
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
      <% end %>
      <% if !@user_is_friend && @user != current_user%>
      <%= link_to "Follow", friends_path(id: @user.id), method: :post,  class: "btn btn-outline-dark common-btn edit-profile-btn" %>
      <% end %>
      <% if @user_is_friend && @user != current_user%>
      <%= link_to "Unfollow", friend_path(id: @user.id), method: :delete,  class: "btn btn-outline-dark common-btn edit-profile-btn" %>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <div class="card-body">
                <%= form_for @user, :html => {:class => "dropzone upload-images p-0 border-0",method: :put, url: user_path} do |f| %>
                <div class="fallback">
                  <%= file_field_tag :image, type: :file%>
                </div>
                <div class="dropzone-previews mb-3">
                  <div class="upload-photos-icon">
                    <i class="fa fa-plus fa-2x" aria-hidden="true" style="color:#dddfe2"></i>
                  </div>
                </div>
                <%= f.submit "Update avatar", class: "btn btn-primary" %>
                <% end %>
              </div>
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <p class="email"><%= @user.email %></p>
    </div>
  </div>

  <div class="profile-tab">
    <% if @user == current_user %>
    <nav>
      <div class="nav nav-tabs d-flex justify-content-center" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-posts-tab" data-toggle="tab" href="#nav-posts" role="tab" aria-controls="nav-posts" aria-selected="true">POSTS</a>
        <a class="nav-item nav-link" id="nav-saved-tab" data-toggle="tab" href="#nav-saved" role="tab" aria-controls="nav-saved" aria-selected="false">SAVED</a>
      </div>
    </nav>
    <% end %>
    <div class="tab-content pb-3" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-posts" role="tabpanel" aria-labelledby="nav-posts-tab">
        <div class="row">
          <%= render "post", {posts: @posts} %>
        </div>
      </div>
      <div class="tab-pane fade" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
        <div class="row">
          <%= render "post", {posts: @saved} if @user == current_user %>
        </div>
      </div>
    </div>
  </div>
</div>